### PR TITLE
Fix errors linked to TrackMate v7 series.

### PR DESCRIPTION
**Pull request by tinevez**

### CODE REVIEW

**Comment by tischi** [comment]
@tinevez I fixed the `SparseLAPTrackerFactory` import here: https://github.com/tischi/fiji-plugin-FISH/tree/fix-trackmate

1. Do you know whether I could have somehow pushed this fix "into your PR"?
2. I really need the spots of the different channels to have different colours; any ideas for how to achieve this? There is/was a way to change the colour of spots, is it? If you would just add a comment in the code where I could assign the colour I can try more myself.

**Comment by tischi** [comment]
ad 1) I tried to rebase your PR that it does not go into master, but into my fix-trackmate branch, but github would not let me do it; can you try?

**Comment by tinevez** [comment]
Hello @tischi 
Yes it compiles on my side. I suspect something fishy with the pom versions. 
I will try to rebase my PR so that you can merge it.

**Comment by tinevez** [comment]
I do not have merge rights on your repo, but normally everything is setup. You just have to merge this PR for instance here in github.

**Comment by tischi** [comment]
OK, thanks @tinevez!

Any suggestions about how to colour the spots for the different channels? I can fake something, e.g. give them some fake property, e.g. spot size, by which I colour.

**Comment by tinevez** [comment]
We would need to store what channels are the spots created on. 
But I think the fastest way would be to directly use the MANUAL_COLOR feature. Here you just specify what color you want to use, specified as an `int`.

https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/features/manual/ManualSpotColorAnalyzerFactory.java

It's one of the lesser known feature of TrackMate but could be a perfect fit if you are ok to specify color 'manually' in your code.

Screenshot 2023-06-07 at 12 59 23

**Pull request merged**
